batches_per_eval: 1407
cfg.hidden_size: 256
cfg.in_channels: 4
cfg.intermediate_size: 128
cfg.latent_size: 16
cfg.max_dist: 500
cfg.num_refine_iters: 2
cfg.num_rings: 6
cfg.num_samples: 3
cfg.num_wedges: 6
cfg.obs_len: 60
cfg.out_channels: 16
cfg.pred_dim: 2
cfg.pred_len: 30
cfg.rmin: 5
is_tuning: false
lr: 0.0003
model_class: DESIREModule
training.batch_size: 1024
training.early_stopping_patience: 10
training.max_epochs: 30
training.max_seconds: null
warmup_batches: 1407
weight_decay: 1.0e-05
