batches_per_eval: 1407
cfg.edge_feat_dim: 25
cfg.gnn_hidden_size: 64
cfg.gnn_n_head: 4
cfg.map_cnn_in: 4
cfg.map_cnn_out: 128
cfg.map_radius: 500
cfg.map_res: 50
cfg.max_dist: 500
cfg.mdn_modes: 3
cfg.node_feat_dim: 8
cfg.obs_len: 60
cfg.pred_len: 30
cfg.prior_cnn_out: 128
cfg.prior_pred_scope: path
cfg.rnn_hidden_size: 256
cfg.static_feat_dim: 8
is_tuning: false
lr: 0.0003
model: NereusModule
nereus_modules.map: atte
nereus_modules.prior: path
nereus_modules.social: gat
training.batch_size: 1024
training.early_stopping_patience: 3
training.max_epochs: 30
training.max_seconds: 36000
warmup_batches: 1407
weight_decay: 1.0e-05
