subfolder: "fhkiel_test"
raw_data_src: "fhkiel"      # dma or fhkiel

geo_data:
    local_crs: "EPSG:25832"
    area_crs: "EPSG:3035"
    tif_res: 10.0
    bboxes:
        kiel: [10.12, 54.31, 10.33, 54.46]
        # kiel_eck:  [9.8, 54.3, 10.4, 54.6]
        # odense: [10.42, 55.42, 10.68, 55.55]
        # kolding: [9.46, 55.43, 9.84, 55.58]
        # sonderborg: [9.73, 54.87, 9.83, 54.93]

process:
    drop_outlier:
        max_speed_(kn): 40
        max_consecutive_outliers: 3
    splitter:
        observation_gap:
            duration_turn_(s): 120
            duration_stright_(s): 300
        speed:
            duration_(s): 3600
            min_speed_(kn): 0.6
            duration_post_interpol_(s): 60
        stop:
            duration_(s): 300
            diameter_(m): 100
            
    interpolate:
        step_size_(s): 5
        pre_min_traj_len: 10
        post_min_traj_len: 48

features:
    ship2ship:
        max_dist_(m): 2000