# for pandas to handle NaNs use the following types: 
# Int64, Float64, boolean, string, category, datetime

# "/data1/aistraj/ais/ais/raw"  "data/kiel/ais/1_raw"
# "/home/bbiesenbach/data/kiel/ais/2_decoded"   "data/kiel/ais/2_decoded"

paths:
    in_folder: "/data1/aistraj/ais/ais/raw"
    out_folder: "data/kiel/ais/2_decoded"

tables:
    traj:
        msg_types: [1, 2, 3, 18, 19]
        column_types:
            mmsi: Int64
            timestamp: datetime
            lon: Float64
            lat: Float64
            speed: Float64
            course: Float64
            heading: Int64
            status: Int64
            turn: Int64
            maneuver: Int64
            accuracy: boolean
            raim: boolean

    ship:
        msg_types: [5, 24]
        column_types:
            mmsi: Int64
            timestamp: datetime
            ship_type: Int64
            imo: Int64
            to_bow: Int64
            to_stern: Int64
            to_port: Int64
            to_starboard: Int64
            draught: Float64
            destination: string