batches_per_eval: 5628
cfg.attn_dropout: 0.1
cfg.dropout: 0.1
cfg.max_dist: 0
cfg.n_cog_embd: 32
cfg.n_embd: 256
cfg.n_head: 8
cfg.n_layer: 4
cfg.n_sog_embd: 32
cfg.n_x_embd: 96
cfg.n_y_embd: 96
cfg.num_samples: 3
cfg.obs_len: 60
cfg.pos_res: 25
cfg.pred_len: 30
cfg.r_vicinity: 8
cfg.sample_mode: vicinity
cfg.temperature: 1.0
cfg.top_k: null
is_tuning: false
lr: 0.0006
model_class: TrAISformerARModule
training.batch_size: 256
training.early_stopping_patience: 3
training.max_epochs: 30
training.max_seconds: 36000
warmup_batches: 5628
weight_decay: 1.0e-05
